---
title: "User Guide"
---

This user guide provides examples and a more in-depth guide to using `earthaccess` to search for datasets and data files, and to access data files when working locally or in the cloud.


## Authentication

To access NASA data, you have to login using your Earth Data Login credentials.  You can register for a free Earth Data Login account [here](https://urs.earthdata.nasa.gov/).

By default, `earthaccess` will look for your Earth Data Login credentials in a `.netrc` file, or in environment variables `$EARTHDATA_USERNAME` and `$EARTHDATA_PASSWORD`.  If you don't
have either of these set up, you can login manually.  See [Authenticating](authenticate.qmd) to learn how to create a `.netrc` file or environment variables.

Running the following code will authenticate using your EarthData
Login credentials.  By default, `login` will first check if you have
`$EARTHDATA_USERNAME` and `$EARTHDATA_PASSWORD` environments variables
set, then it will check if you have a `.netrc` file in your `$HOME`.
Finally, it will prompt for user input.

_Is it necessary to save the returned `__auth__` object?_

```
earthaccess.login()
```

### Authenticating using environment variables



## Search for data sets


## Search for data


## Download data to a local machine


## Working in the cloud